title: Data Science Project
#description: This is an example I am working on
theme: jekyll-theme-minimal
# URL image link

![Image URL](https://i0.wp.com/statisticsbyjim.com/wp-content/uploads/2020/07/TimeSeriesTrade.png)
